export const THEME_MODES = {
  ocean: {
    label: "Ocean",
    primary: "#355872",
    secondary: "#7AAACE",
    tertiary: "#9CD5FF",
    text: "#F7F8F0",
  },
  classic: {
    label: "Classic",
    primary: "#0f172a",
    secondary: "#334155",
    tertiary: "#6366f1",
    text: "#f8fafc",
  },
  coral: {
    label: "Coral",
    primary: "#F4F0E4",
    secondary: "#44A194",
    tertiary: "#537D96",
    text: "#EC8F8D",
  },
  periwinkle: {
    label: "Periwinkle",
    primary: "#4A55A2",
    secondary: "#7895CB",
    tertiary: "#A0BFE0",
    text: "#C5DFF8",
  },
  forestInk: {
    label: "Forest Ink",
    primary: "#EDE6DB",
    secondary: "#1D5C63",
    tertiary: "#1D5C63",
    text: "#1A3C40",
  },
  slateMist: {
    label: "Slate Mist",
    primary: "#2C3E50",
    secondary: "#34495E",
    tertiary: "#ECF0F1",
    text: "#BDC3C7",
  },
  violetIce: {
    label: "Violet Ice",
    primary: "#6F38C5",
    secondary: "#87A2FB",
    tertiary: "#ADDDD0",
    text: "#EEEEEE",
  },
  popArt: {
    label: "Pop Art",
    primary: "#EAEC96",
    secondary: "#43C0AC",
    tertiary: "#A93199",
    text: "#FA0559",
  },
  amberNight: {
    label: "Amber Night",
    primary: "#FFF0DC",
    secondary: "#F0BB78",
    tertiary: "#543A14",
    text: "#131010",
  },
};
